### PR TITLE
Changes, changes, changes

### PR DESCRIPTION
**Pull request by Lordmau5**
Found out that the downloader works with free accounts as well.

ID3-Tagging didn't work properly for me with ffmetadata, so I swapped it for node-id3.

Also, fixed the rate-limit on free accounts.
Once it runs into it, it's waiting for 10 seconds and tries again.
This is looping up until it can download.

Fixed the amount of songs that are being fetched from a playlist from 100 to 9001 (should be enough, right?)

Also, if a song is not available anymore it ran into a 404 error, causing the whole program to **STOP**.
This is fixed now.
It's trying to find alternatives for the song, and if it can't find any, it will just skip the song.

I dropped the Coffeescript files because I couldn't be arsed to work on them.
Didn't look into Coffeescript yet, and sadly I don't really want to either.

Enjoy!

### CODE REVIEW

**Comment by Lordmau5** [comment]
Found out that once a free account reaches the rate-limit, it's able to download 10 songs per 20-30 seconds.
So there's that.

**Comment by JoseHidalgo** [comment]
Hi, I didn't found any another way of contacting you.
For some reason your software won't work at all in my computer.
- I have installed MS Framework v4.6.1
- I have installed nodejs (in Program Files - I am running W7 SP1 x64)
- I have started Spotify Downloader, then logged in using my Spotify login/password (no FB login)
- I have found my Spotify playlist URL (right click on the playlist, then "copy Spotify URL").
- I have pasted the copied URL into Spotify Downloader, then clicked on Download
- Then... absolutely NOTHING happens. Not even an error. NOTHING. And nothing is downloaded of course.
  Since nothing happens, I can't report on anything. Maybe your app should be a little more verbose than that ?
  I am willing to do more testing if required. Feel free to reply. Thank you.

**Comment by Lordmau5** [comment]
Well, I haven't done anything in regards to the GUI.
That's @dekiller82 's work.

You could try running it manually via. the command line.
If _that_ works, then it is some issue in the GUI code.

On the other hand, I'd recommend you to wait for 0.0.3 because it will have some massive code changes.

Another thing:
Issues regarding my fork of this project can now be posted on this repo here:
https://github.com/Lordmau5/spd-issues/issues

**Comment by serjum** [comment]
@Lordmau5, thanks for your contribution, I have used partially code from your commit.
@JoseHidalgo, I have tested on Windows XP an work perfectly from cmd. 
Installing steps:
- Install nodeJs
- Download zip or git clone module (https://github.com/serjum/spotify-playlist-downloader/archive/master.zip or https://github.com/serjum/spotify-playlist-downloader.git)
- unzip
- from Node.js command prompt go to unzipped folder and do node install
- to use module enter: node main.js -u YOURUSR -p YOURPASS -l spotify:user:spotify:
  laylist:BLABLABLA...

Enjoy! ;)

**Pull request closed without merging**
